### ISSUE TITLE
:clown_face: 占个 issue 坑

### ISSUE THREAD

**Issue by ghost** [Teeoo/v2p-client#3]
# 2021-12-02 ~

## TASK

- [x] 1. 界面每页展示任务数希望能保留，例如此次设置 20，下次还是 20

  ![image](https://user-images.githubusercontent.com/62660101/144394525-150b43b4-a771-4b99-836f-3758d654824b.png)

- [x] 2. 支持搜索筛选等快速定位功能

  - ~~任务支持自定义分组，例如分组 A：elecV2P 系统任务 B: 羊毛 C: 其他。参考原版 3.6.3 色块区分和折叠~~

- [x] 3. [黑暗模式](https://github.com/Teeoo/v2p-client/issues/3#issuecomment-984544352)

- [x] 4. [位置微调](https://github.com/Teeoo/v2p-client/issues/3#issuecomment-984796592)

**Comment by Teeoo** [comment]
task要大改我还没想好咋改分组应该不会支持会支持搜索

**Comment by ghost** [comment]
@Teeoo 也行，能达到快速定位的目的就可以，其他也是如此

**Comment by ghost** [comment]
# 2021-12-02 02

## UI

- [x] 暗黑模式嘻嘻嘻😬

**Comment by ghost** [comment]
# 2021-12-03 01

## UI

- [x] 1. 位置微调

  ![image](https://user-images.githubusercontent.com/62660101/144464020-68256870-e65f-446b-a588-22eca41f1f68.png)

**Comment by ghost** [comment]
# 2021-12-05 01

## SETTING

~~- [ ] 开机自动运行自定义脚本，如依赖安装类，希望支持 Shell 等更多类型~~ 放弃

**Comment by Teeoo** [comment]
我该怎么满足你这个无理需求
👨
🎽
👖
